### ISSUE TITLE
DrugBank vs. ChEMBL

### ISSUE THREAD

**Issue by ChristopherWilks** [mims-harvard/PrimeKG#13]
Hi,

First, thanks for a great resource, PrimeKG is super useful!

I was wondering if you'd be willing to share the motivation to use DrugBank vs. ChEMBL?

I'm trying to decide if it's worth it for my company to buy a license to DrugBank or if we can find most of what we need already in ChEMBL.

Thanks,
Chris

**Comment by payalchandak** [comment]
Hi Chris,

Thank you for your kind words about PrimeKG! The decision to utilize DrugBank over ChEMBL was influenced by several factors. Firstly, DrugBank offers a comprehensive and meticulously curated database, with detailed drug data including mechanisms of action, mapping to ATC codes, and drug-drug interactions, which is crucial for our project requirements. Secondly, the quality of data in DrugBank is well-regarded among experts, and its user-friendly interface facilitates easy navigation and extraction of information. Additionally, DrugBank provides a robust API which significantly eases the integration into our system.

Hope this helps!
