### ISSUE TITLE
All edges seem to be duplicated in pre-build data files

### ISSUE THREAD

**Issue by martytom** [mims-harvard/PrimeKG#14]
When following the instructions as described in the `README.md` to load PrimeKG, the resulting dataframe has 8,100,498 edges/triples instead of the reported 4,050,249. 

So running 

```python
import pandas as pd
primekg = pd.read_csv('kg.csv', low_memory=False)
primekg.query('y_type=="disease"|x_type=="disease"')

print(len(primekg))
```
gives

```
8100498 rows × 10 columns
```

It seems that every triple appears twice in the data in source/target swapped form (what makes sense, given that the resulting dataframe contains exactly twice as many triples as reported in the `README.md`). The column swapped triples do not seem to have inverse relationships (what might cause problems in ML applications). In fact, the labels are identical, just the source and target columns are swapped.

Moreover, it looks like there exist 370 duplicates for the drug_protein label as can be seen by running 
```python
primekg[primekg.duplicated()]
``` 
what gives

```
370 rows × 10 columns
```

Also when loading the graph from `pykeen.datasets`, the number of triples exceeds the reported 4.5 million. 

```python
from pykeen.datasets import PrimeKG
dataset = PrimeKG()
print(dataset.training.num_triples + dataset.validation.num_triples + dataset.testing.num_triples)
```
shows that the data has 8,099,991 triples.

Given that the source/target swapped edges do not come with a new, i.e., reverse relationship, it might come to problems in ML applications when using the unfiltered data with the ~8.1 million edges.

**Comment by ayushnoori** [comment]
Hi @martytom, thanks for your comment. PrimeKG is an undirected graph $G = (V, E)$, so all edges are bidirectional in nature. Thus, it is expected that there will be twice as many rows in the data frame as number of edges in the graph, one for the forward direction $(u, v) \in E$ and one for the reverse direction $(v, u) \in E$. The edge type labels are given at the edge label, so are identical for both directions. However, you can easily distinguish between forward and reverse edges by concatenating the `x_type` and `y_type` columns.

When I load PrimeKG, the shape of the data frame is `(8100498, 12)` (*i.e.*, 8100498 rows × 12 columns). I can't seem to reproduce your edge duplication error, please see below:

![image](https://github.com/mims-harvard/PrimeKG/assets/43010710/da9aab8d-fda0-4cd1-b538-9c16c4e5f0eb)

Thanks for the pointer that a few (approx. 250) edges may be missing when importing PrimeKG from `pykeen`. @payalchandak and I will look into this; for now, if you seek to use the 2021 version of PrimeKG, we recommend using the stable version of the graph provided via [Harvard Dataverse](https://doi.org/10.7910/DVN/IXA7BM).
