### ISSUE TITLE
Can PrimeKG be used for commercial purposes?

### ISSUE THREAD

**Issue by FaizanFaisal25** [mims-harvard/PrimeKG#16]
I'm seeking clarification regarding the licensing terms for PrimeKG. It appears there is a contrast in licensing, as the repository is dependent on the non-commercial-use database Drugbank, while PrimeKG operates under an MIT License. I would appreciate some insights to address this inconsistency.

**Comment by payalchandak** [comment]
Thanks for your question. PrimeKG codebase and associated tools are released under the MIT license. Please note that this license specifically refers to the PrimeKG software, and is distinct from any licenses governing the PrimeKG dataset itself. For individual dataset usage, refer to the respective dataset licenses available on data website.
