### ISSUE TITLE
PrimeKG vs Hetionet vs MSI

### ISSUE THREAD

**Issue by pgniewko** [mims-harvard/PrimeKG#17]
How does PrimeKG relate to [HetioNet](https://het.io/), which appears to be a smaller knowledge graph? For example, there might be variations in the definitions of diseases or in aggregation rules. HetioNet is also considered a state-of-the-art (SOTA) knowledge graph, yet it wasn’t discussed in the original paper.

Similarly, the Multiscale Interactome ([MSI](https://github.com/snap-stanford/multiscale-interactome)) was developed some time ago and also wasn’t included in the main paper, despite being co-developed by the author of PrimeKG.

Is it reasonable to assume that both HetioNet and MSI are substantially incorporated within PrimeKG, barring differences in ontology definitions?

**Comment by tkmamidi** [comment]
I see it is closed but wondering what the answer for this question is....
