### ISSUE TITLE
Escaped double quotes in `disease_features.csv`

### ISSUE THREAD

**Issue by mvelimir** [mims-harvard/PrimeKG#18]
Why do some fields contain a backslash before the double quote at the end of the field? When trying to import the file in Neo4j I first have to remove all backslashes before double quotes, because otherwise it escapes the double quote.

<img width="1476" alt="image" src="https://github.com/mims-harvard/PrimeKG/assets/81649656/d7579bb5-357f-467e-bd5f-a7c4b1ba4dcd">

**Comment by ayushnoori** [comment]
Hi @mvelimir, could you please give us a few specific examples and the exact `.csv` file you're referring to? I don't believe we've encountered this problem ourselves but would be happy to look into this. Thanks.

cc: @payalchandak

**Comment by payalchandak** [comment]
Can't reproduce

**Comment by sdhutchins** [comment]
Hi @payalchandak @ayushnoori!

Are there examples of importing the csvs into neo4j?
