### ISSUE TITLE
FAIR url to download TSV files

### ISSUE THREAD

**Issue by LucaCappelletti94** [mims-harvard/PrimeKG#2]
Hello, and thank you for creating this resource.

I wanted to add this dataset to [the graph retrieval of my library](https://github.com/AnacletoLAB/grape), but I cannot find permanent URLs.
The ones that [are made available here](https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/IXA7BM) seem to be short-lived.

Thanks!
Luca

**Comment by payalchandak** [comment]
Hi Luca, 

Thanks for reaching out! The way to get permanent urls on [Harvard Dataverse](https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/IXA7BM) is to click on the file of interest, navigate to metadata, and get the "Download URL".

For example, you can use this purl "https://dataverse.harvard.edu/api/access/datafile/6180620" to access the kg.csv file found [here](https://dataverse.harvard.edu/file.xhtml?fileId=6180620&version=2.1). The following command will let you download the file locally: 

`wget -O kg.csv https://dataverse.harvard.edu/api/access/datafile/6180620`

Hope this helps! 

Best, 
Payal
