### ISSUE TITLE
support query service?

### ISSUE THREAD

**Issue by HarrialX** [mims-harvard/PrimeKG#4]
Hi Dear Author,

Thanks for releasing this brilliant KG! I just wonder if there is any API deployment using your KG as the backend data, and supporting users to query this KG? For example, by querying some evidence (entity names) and relations, the API can find corresponding answers from the KG, probably using some machine learning techniques. I'm curious whether you've built such a "query service"?

**Comment by payalchandak** [comment]
Hello, 

Thanks for reaching out with this wonderful idea! I am a full time PhD student so I have not focused on building an API for this resource -- however, if you are interested, I would love to collaborate on this effort and support as best as I can! 

Best,
Payal
