### ISSUE TITLE
Disease ontology incorrect

### ISSUE THREAD

**Issue by Oppengame** [mims-harvard/PrimeKG#5]
Hi, 
Some of parent-child relations in disease ontology seem to be incorrect. 
For instance, we have Short bowel disorder both as a parent (which is correct) and **as a child** for Primary short bowel syndrome. 
Perhaps all child-parent relations appear as parent-child, hence it is impossible to build the hierarchy.

**Comment by payalchandak** [comment]
Hi, thank you for pointing this out. Unfortunately, we did not build the original disease ontology relations but we are just reading them. This would be great feedback for those managing disease ontology: https://disease-ontology.org
