### ISSUE TITLE
`kg.csv` load error

### ISSUE THREAD

**Issue by abearab** [mims-harvard/PrimeKG#6]
I followed [this part](https://github.com/mims-harvard/PrimeKG#getting-started-in-python) and I got bellow error:

```python
primekg.query('node_type=="disease"')
```
```
UndefinedVariableError: name 'node_type' is not defined
```

**Comment by abearab** [comment]
I kind of like this according to your current column names.
```python 
primekg.query('y_type=="disease"|x_type=="disease"')
```

**Comment by payalchandak** [comment]
Thanks for pointing this out, I have updated the README!
