### ISSUE TITLE
Install fails because `requirements.txt` contains hard coded paths

### ISSUE THREAD

**Issue by bevankoopman** [mims-harvard/PrimeKG#7]
`pip3 install -r requirements.txt` fails as `requirements.txt` contains hard coded file paths. Error is:

```
ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: '/opt/conda/conda-bld/attrs_1642510447205/work'
```

**Comment by abearab** [comment]
I could use `conda` to build an environment with this file https://github.com/mims-harvard/PrimeKG/blob/main/environment.yml

**Comment by valkx** [comment]
same issue experienced as indicated by @bevankoopman requirements.txt refers to /opt/conda location. requirements.txt is not formatted for a pip install.

**Comment by payalchandak** [comment]
Please review our recent code update. This issue should be fixed using the [updated_requirements.txt](https://github.com/mims-harvard/PrimeKG/blob/main/updated_requirements.txt) file. Please open a new issue if there are problems with the new file.
