### ISSUE TITLE
Lack of files

### ISSUE THREAD

**Issue by gsh150801** [mims-harvard/PrimeKG#8]
When I execute drugbank_drug_protein.py file, it failed because of lacking of  '../data/vocab/gene_map.csv' and  '../data/vocab/drugbank_vocabulary.csv'.

**Comment by shahrajani** [comment]
hey
I am having same issue, am not able to get below files:
gene_map.csv
drugbank_vocabulary.csv
parsed/chemical-taxonomy.txt
if any of you able to get these please share.

**Comment by payalchandak** [comment]
This issue should be resolved in the July 2023 update. Please see the `datasets/primary_data_resources.sh` bash script to download resources.

**Comment by ayushnoori** [comment]
Hi @dhilst, you may still need `protein_protein.csv`. Please see a link to the file below:

[protein_protein.csv](https://github.com/mims-harvard/PrimeKG/files/12064934/protein_protein.csv)

**Comment by ayushnoori** [comment]
Hi @JamerryShan -- please replace the hardcoded paths in [`primary_data_resources.sh`](https://github.com/mims-harvard/PrimeKG/blob/main/datasets/primary_data_resources.sh) with your own local paths after downloading the datasets yourself using the provided URLs to the primary source datasets.

For example, replace:
```
/n/data1/hms/dbmi/zitnik/lab/users/an252/PrimeKG
```
with
```
<path to where you cloned the repo>/PrimeKG
```

**Comment by ayushnoori** [comment]
Yes, you would need to obtain your own DrugBank license and download the DrugBank database locally yourself; then, you can replace that path with your own.

**Comment by ayushnoori** [comment]
Hi Junjie, thanks for your email. @payalchandak and I have both been trying to email you back but unfortunately our messages don't seem to be getting through:

<img width="663" alt="image" src="https://github.com/mims-harvard/PrimeKG/assets/43010710/df55553a-5f33-4336-b14f-a9fc83fff1c8">


Is there another email address that we can reach you at?

**Comment by ayushnoori** [comment]
Sure, we will reach out!

**Comment by dataartist-og** [comment]
Just commenting to add that I can't see where parsed/chemical-taxonomy.txt is coming from. It is assumed to exist in the same `parsed` directory which contains the output of the parsexml_drugbank.ipynb ; However it seems that chemical-taxonomy.txt is NOT produced by the script. Please advise on how I can remedy this! I could create a PR if needed with the update, if I get some guidance on the matter. Thanks
<img width="1155" alt="Screenshot 2024-06-14 at 6 53 11 PM" src="https://github.com/mims-harvard/PrimeKG/assets/79862447/7c725a75-c8c0-46c1-bceb-acfcb939faac">

**Comment by dataartist-og** [comment]
> hey I am having same issue, am not able to get below files: gene_map.csv drugbank_vocabulary.csv parsed/chemical-taxonomy.txt if any of you able to get these please share.

@shahrajani did you ever get this sorted? specifically missing the parsed/chemical-taxonomy.txt
