### ISSUE TITLE
Are there any OMIM nodes?

### ISSUE THREAD

**Issue by abearab** [mims-harvard/PrimeKG#9]
I'm trying to use your knowledge graph and I wanted to hear your thoughts about OMIM, especially their link with the HPO term. Is that already covered? How I'm supposed to extract that information? I couldn't find that in the `csv` file you already linked in this repo.

___
> Since the MONDO Disease Ontology[44](https://www.nature.com/articles/s41597-023-01960-3#ref-CR44) harmonizes diseases from a wide range of ontologies, including the __Online Mendelian Inheritance in Man (OMIM)__[49](https://www.nature.com/articles/s41597-023-01960-3#ref-CR49), SNOMED Clinical Terms (CT), International Classification of Diseases (ICD), and Medical Dictionary for Regulatory Activities (MedDRA), it was our preferred ontology for defining diseases.

**Comment by abearab** [comment]
**Gene, Disease, Phenotype Relation (GDPR)** dataset (see [this link](https://github.com/CLU-UML/Generic-and-Trend-aware-Curriculum-GNNs#data)) covers such relationships; from @CLU-UML / @amirieb group.

**Comment by payalchandak** [comment]
To the best of my knowledge, OMIM nodes would be considered disease nodes in PrimeKG. They are part of the MONDO disease ontology that harmonizes many resources (including OMIM). You can read more about this [here](https://mondo.monarchinitiative.org).

**Comment by abearab** [comment]
Yeah, that makes sense. However, the OMIM database consists of entries describing phenotypes and genes. What motivated me to open this issue was a direct representation of them at primeKG as nodes in relationship to other node types. I can consider them as part of MONDO for my research purposes and move forward. Thank you for the response.

**Comment by abearab** [comment]
I would like to reopen this issue according to my more in-depth exploration. To my understanding, MONDO (and similarly HPO) only covers part of the information covered in the OMIM database. Thus, I think it's a useful add-on for this tool to cover more information from OMIM to empower extra tasks related to rare genetic disorders.

Following up on my recent meeting with @marinkaz, I'll submit a pull request to cover this issue by extending PrimeKG with an OMIM-KG. 

___
<img width="400" alt="image" src="https://github.com/mims-harvard/PrimeKG/assets/53412130/8a714580-0234-4021-a34c-12354d211a5a">

**Comment by ayushnoori** [comment]
Merged, please see PR https://github.com/mims-harvard/PrimeKG/pull/12 for a detailed review and plan for future improvements.
